jackrabbit:
  image: node
  working_dir: /code
  command: ['npm install', 'npm test']
  volumes:
    - .:/code
  links:
    - rabbit
  environment:
    RABBIT_URL: 'amqp://rabbit'
rabbit:
  image: rabbitmq
